apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  project: homework
  source:
    repoURL: https://github.com/Kuber-2024-02OTUS/AV86github_repo
    targetRevision: HEAD
    path: kubernetes-networks
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true