apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homework
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Otus homework
  sourceRepos:
  - 'https://github.com/Kuber-2024-02OTUS/AV86github_repo'
  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'