apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ""
  resources:
    requests:
      storage: 2Mi